'use strict';

const button = document.querySelector('.button');
const p = document.querySelector('.excuse');
const reset = document.querySelector('.reset');

const who = [
  'Bad Bunny',
  'El perro',
  'Mi abuela',
  'Mi prima segunda',
  'Una tortuga',
];
const action = ['lanzó', 'quemó', 'pintó', 'se comió', 'desmontó'];
const what = [
  'mis deberes',
  'mi teléfono',
  'mi ordenador',
  'mis ganas de vivir',
  'mi casa',
];
const when = [
  'mientras dormía',
  'ayer',
  'esta mañana',
  'el año pasado',
  'el mes pasado',
];
const how = [
  'sin darme cuenta',
  'suavemente',
  'despacito',
  'mientras comía cocido',
  'perreando',
];
//Matches the random position generated by getRandom to each array and renders the excuse.

function getExcuse() {
  let sentenceParts = [who, action, what, how, when];
  let excuse = '';

  for (let item in sentenceParts) {
    excuse = excuse + getRandom(sentenceParts[item]) + ' ';
  }
  p.innerHTML = excuse;
}

//Gets a random position in our array
function getRandom(elements) {
  let position = Math.floor(Math.random() * elements.length);
  return elements[position];
}

function resetP() {
  p.innerHTML = 'No te lo vas a creer, pero...';
}

button.addEventListener('click', getExcuse);
reset.addEventListener('click', resetP);
